/**
 * @description       :
 * @author            : admillican08@gmail.com
 * @group             :
 * @last modified on  : 09-12-2024
 * @last modified by  : admillican08@gmail.com
 **/

public class JoobleJob {
  public String title;
  public String location;
  public String description;
  public String salary;
  public String source;
  public String type;
  public String link;
  public String company;
  public String updated;
  public String id;
}
